export const questionCategories = [
  {
    id: "surface",
    label: "Surface Level",
    color: "bg-green-100 text-green-700 border-green-200",
    dot: "bg-green-500",
    description: "Warm-up questions to ease in and get a feel for day-to-day patterns",
  },
  {
    id: "behavioral",
    label: "Behavioral Patterns",
    color: "bg-yellow-100 text-yellow-700 border-yellow-200",
    dot: "bg-yellow-500",
    description: "How you tend to act and react in different situations",
  },
  {
    id: "communication",
    label: "Communication Style",
    color: "bg-blue-100 text-blue-700 border-blue-200",
    dot: "bg-blue-500",
    description: "How you prefer to give and receive information",
  },
  {
    id: "emotional_triggers",
    label: "Emotional Triggers",
    color: "bg-orange-100 text-orange-700 border-orange-200",
    dot: "bg-orange-500",
    description: "What activates strong emotional responses in you",
  },
  {
    id: "conflict_style",
    label: "Conflict Style",
    color: "bg-red-100 text-red-700 border-red-200",
    dot: "bg-red-500",
    description: "How you engage with, avoid, or move through conflict",
  },
  {
    id: "energy_social",
    label: "Energy & Social Needs",
    color: "bg-teal-100 text-teal-700 border-teal-200",
    dot: "bg-teal-500",
    description: "How you recharge and what drains or energizes you",
  },
  {
    id: "deep_reflection",
    label: "Deep Reflection",
    color: "bg-purple-100 text-purple-700 border-purple-200",
    dot: "bg-purple-500",
    description: "Honest introspection about yourself, your needs, and your history",
  },
  {
    id: "family_upbringing",
    label: "Family & Upbringing",
    color: "bg-pink-100 text-pink-700 border-pink-200",
    dot: "bg-pink-500",
    description: "How your past shaped the way you love and relate",
  },
  {
    id: "partner_perception",
    label: "Partner Perception",
    color: "bg-indigo-100 text-indigo-700 border-indigo-200",
    dot: "bg-indigo-500",
    description: "How you think your partner experiences you",
  },
  {
    id: "needs_vulnerability",
    label: "Needs & Vulnerability",
    color: "bg-rose-100 text-rose-700 border-rose-200",
    dot: "bg-rose-500",
    description: "What you need most — and what's hardest to ask for",
  },
  {
    id: "then_vs_now",
    label: "Then vs Now",
    color: "bg-slate-100 text-slate-700 border-slate-200",
    dot: "bg-slate-500",
    description: "How you've changed over 13 years — and what patterns remain",
  },
];

export const questions = [

  // ─── SURFACE ───────────────────────────────────────────────────────────────

  {
    id: "s1",
    category: "surface",
    text: "How do you usually react when plans change unexpectedly?",
    type: "choice",
    options: ["Go with the flow", "Feel slightly annoyed but adapt", "Get frustrated", "Need time to process", "Depends on what changes"],
    tags: ["adaptable", "control_preference", "frustration_trigger"],
    weight: "medium",
  },
  {
    id: "s2",
    category: "surface",
    text: "What does a perfect evening together look like for you right now?",
    type: "text",
    tags: ["recharge_style", "quality_time", "love_language"],
    weight: "medium",
  },
  {
    id: "s3",
    category: "surface",
    text: "When you're stressed, what helps you decompress the most?",
    type: "choice",
    options: ["Being alone", "Talking it out", "Physical activity", "Distraction (TV, phone, music)", "Affection from partner", "Getting outside"],
    tags: ["stress_response", "recharge_style", "withdrawal"],
    weight: "high",
  },
  {
    id: "s4",
    category: "surface",
    text: "How important is routine and structure to your daily life?",
    type: "scale",
    tags: ["structure_need", "flexibility", "control_preference"],
    weight: "medium",
  },
  {
    id: "s5",
    category: "surface",
    text: "When you're in a good mood, how do you usually show it?",
    type: "choice",
    options: ["I get affectionate", "I talk more", "I become more playful", "I suggest doing something together", "I just feel lighter but don't show much"],
    tags: ["emotional_expression", "love_language"],
    weight: "low",
  },
  {
    id: "s6",
    category: "surface",
    text: "How do you tend to handle a bad day before you've said a word about it?",
    type: "choice",
    options: ["Go quiet", "Drop hints", "Need to vent immediately", "Try to shake it off", "Expect my partner to notice"],
    tags: ["stress_response", "emotional_expression", "partner_perception"],
    weight: "high",
  },
  {
    id: "s7",
    category: "surface",
    text: "How much alone time do you need on a typical week?",
    type: "scale",
    tags: ["social_energy", "need_for_space", "recharge_style"],
    weight: "high",
  },
  {
    id: "s8",
    category: "surface",
    text: "How do you feel about spontaneous plans or surprises?",
    type: "choice",
    options: ["Love them — exciting", "Usually fine if low-pressure", "Prefer to know in advance", "Really dislike them", "Depends on my stress level that day"],
    tags: ["control_preference", "flexibility", "stress_trigger"],
    weight: "medium",
  },

  // ─── BEHAVIORAL ────────────────────────────────────────────────────────────

  {
    id: "b1",
    category: "behavioral",
    text: "When you're frustrated, what do you tend to do first?",
    type: "choice",
    options: ["Withdraw and go quiet", "Talk about it immediately", "Get irritated or snappy", "Avoid the topic entirely", "Try to fix it yourself"],
    tags: ["frustration_response", "withdrawal", "communication_style"],
    weight: "high",
  },
  {
    id: "b2",
    category: "behavioral",
    text: "When you feel unheard in a conversation, how do you typically respond?",
    type: "choice",
    options: ["Repeat myself more forcefully", "Shut down completely", "Change the subject", "Get emotional", "State it clearly once, then let it go"],
    tags: ["misunderstood_trigger", "conflict_style", "emotional_expression"],
    weight: "high",
  },
  {
    id: "b3",
    category: "behavioral",
    text: "What is your go-to coping mechanism when tension builds at home?",
    type: "text",
    tags: ["stress_response", "conflict_avoidance", "coping"],
    weight: "high",
  },
  {
    id: "b4",
    category: "behavioral",
    text: "How do you respond when you feel criticized — even mildly?",
    type: "choice",
    options: ["Get defensive immediately", "Go quiet and withdraw", "Try to explain myself", "Accept it and reflect", "Deflect with humor"],
    tags: ["defensiveness", "sensitivity_to_tone", "criticism_response"],
    weight: "high",
  },
  {
    id: "b5",
    category: "behavioral",
    text: "When something is wrong but you haven't said anything yet, what does that usually look like from the outside?",
    type: "text",
    tags: ["emotional_expression", "passive_communication", "partner_perception"],
    weight: "high",
  },
  {
    id: "b6",
    category: "behavioral",
    text: "How do you handle it when you've made a mistake or hurt someone?",
    type: "choice",
    options: ["Apologize quickly and move on", "Need time to process before apologizing", "Struggle to say sorry even when I know I'm wrong", "Over-apologize and spiral", "Explain my reasoning first, then apologize"],
    tags: ["accountability", "conflict_style", "emotional_processing"],
    weight: "high",
  },
  {
    id: "b7",
    category: "behavioral",
    text: "How often do you replay conversations or arguments after the fact?",
    type: "scale",
    tags: ["post_conflict_pattern", "rumination", "emotional_processing"],
    weight: "medium",
  },
  {
    id: "b8",
    category: "behavioral",
    text: "When you're overwhelmed, what do you do with your obligations?",
    type: "choice",
    options: ["Power through even if it kills me", "Quietly drop things without saying why", "Ask for help", "Communicate that I'm overwhelmed", "Shut down entirely"],
    tags: ["stress_response", "help_seeking", "communication_style"],
    weight: "high",
  },

  // ─── COMMUNICATION ─────────────────────────────────────────────────────────

  {
    id: "c1",
    category: "communication",
    text: "How do you prefer difficult conversations to start?",
    type: "multi_choice",
    options: ["Gently with some context", "Direct and to the point", "Over text first so I can process", "Only when we're both calm", "With a soft check-in first", "Scheduled in advance"],
    tags: ["communication_preference", "emotional_safety", "processing_style"],
    weight: "high",
  },
  {
    id: "c2",
    category: "communication",
    text: "Which communication approach do you respond best to from your partner?",
    type: "choice",
    options: ["Soft and empathetic tone", "Logical and solution-focused", "Humor to lighten the mood", "Written (text/note first)", "Physical reassurance before talking"],
    tags: ["communication_preference", "tone_sensitivity", "love_language"],
    weight: "high",
  },
  {
    id: "c3",
    category: "communication",
    text: "What makes you feel truly heard by your partner?",
    type: "text",
    tags: ["validation_need", "love_language", "communication_need"],
    weight: "high",
  },
  {
    id: "c4",
    category: "communication",
    text: "When something is bothering you, what do you usually do?",
    type: "choice",
    options: ["Bring it up immediately", "Wait for the right moment", "Keep it to myself", "Hint at it indirectly", "Write it out before saying it"],
    tags: ["direct_communication", "avoidant_communication", "passive_communication"],
    weight: "high",
  },
  {
    id: "c5",
    category: "communication",
    text: "How do you feel when someone raises an issue with you unexpectedly?",
    type: "choice",
    options: ["Open to it", "Slightly defensive", "Overwhelmed — I shut down", "Need time to process before responding", "Depends on the topic and their tone"],
    tags: ["defensiveness", "processing_style", "trigger_unexpected"],
    weight: "high",
  },
  {
    id: "c6",
    category: "communication",
    text: "How comfortable are you expressing disagreement with your partner?",
    type: "scale",
    tags: ["conflict_comfort", "directness", "emotional_safety"],
    weight: "high",
  },
  {
    id: "c7",
    category: "communication",
    text: "When you need something emotionally, how do you usually ask for it?",
    type: "choice",
    options: ["Ask directly", "Drop hints and hope they notice", "Wait until I'm upset, then bring it up", "I don't usually ask — I expect them to know", "I write it out or text it"],
    tags: ["vulnerability", "unmet_needs", "communication_style"],
    weight: "high",
  },
  {
    id: "c8",
    category: "communication",
    text: "How do you feel about silence during a tense moment?",
    type: "choice",
    options: ["It feels safe — I need it", "I can tolerate it briefly", "It makes me anxious", "It feels like rejection", "It depends on who initiates it"],
    tags: ["silence_interpretation", "processing_style", "sensitivity_to_withdrawal"],
    weight: "high",
  },
  {
    id: "c9",
    category: "communication",
    text: "How much of what you're actually feeling do you usually communicate out loud?",
    type: "scale",
    tags: ["emotional_expressiveness", "vulnerability", "communication_style"],
    weight: "high",
  },

  // ─── EMOTIONAL TRIGGERS ────────────────────────────────────────────────────

  {
    id: "e1",
    category: "emotional_triggers",
    text: "What makes you feel most misunderstood?",
    type: "multi_choice",
    options: ["Being interrupted", "Assumptions about my feelings", "Dismissive tone", "Lack of follow-up", "Not being asked how I feel", "Being told to calm down", "Having my experience minimized"],
    tags: ["misunderstood_trigger", "validation_need", "sensitivity_to_tone"],
    weight: "high",
  },
  {
    id: "e2",
    category: "emotional_triggers",
    text: "What tone of voice instantly puts you on the defensive?",
    type: "text",
    tags: ["tone_sensitivity", "defensiveness", "trigger_tone"],
    weight: "high",
  },
  {
    id: "e3",
    category: "emotional_triggers",
    text: "Which situations are most likely to frustrate you in the relationship?",
    type: "multi_choice",
    options: ["Repeating myself", "Feeling ignored or dismissed", "Lack of follow-through on agreements", "Being rushed", "Being criticized in front of others", "Feeling like I'm the only one trying", "Unspoken expectations"],
    tags: ["frustration_trigger", "conflict_trigger", "unmet_needs"],
    weight: "high",
  },
  {
    id: "e4",
    category: "emotional_triggers",
    text: "What tone affects you most negatively?",
    type: "choice",
    options: ["Harsh and blunt", "Dismissive or bored", "Sarcastic", "Cold and withdrawn", "Condescending"],
    tags: ["tone_sensitivity", "emotional_trigger"],
    weight: "high",
  },
  {
    id: "e5",
    category: "emotional_triggers",
    text: "What situation in the relationship makes you feel most vulnerable?",
    type: "text",
    tags: ["vulnerability", "emotional_trigger", "safety_need"],
    weight: "high",
  },
  {
    id: "e6",
    category: "emotional_triggers",
    text: "How sensitive are you to your partner's tone and body language?",
    type: "scale",
    tags: ["sensitivity_to_tone", "emotional_attunement", "trigger_tone"],
    weight: "high",
  },
  {
    id: "e7",
    category: "emotional_triggers",
    text: "When your partner is stressed, how does it affect you?",
    type: "choice",
    options: ["I absorb it and feel stressed too", "I want to fix it immediately", "I give them space instinctively", "I wait to see if they bring it up", "I struggle to not take it personally"],
    tags: ["emotional_absorption", "empathy", "stress_response"],
    weight: "high",
  },
  {
    id: "e8",
    category: "emotional_triggers",
    text: "Is there a specific phrase or word that reliably sets you off? Describe it.",
    type: "text",
    tags: ["trigger_phrase", "emotional_trigger", "sensitivity"],
    weight: "high",
  },

  // ─── CONFLICT STYLE ────────────────────────────────────────────────────────

  {
    id: "cf1",
    category: "conflict_style",
    text: "During conflict, you tend to:",
    type: "choice",
    options: ["Address it immediately regardless", "Take space before engaging", "Escalate emotionally", "Shut down completely", "Try to find middle ground quickly"],
    tags: ["conflict_style", "escalation_pattern", "withdrawal_pattern"],
    weight: "high",
  },
  {
    id: "cf2",
    category: "conflict_style",
    text: "What do you need MOST during a conflict?",
    type: "multi_choice",
    options: ["To be heard without being interrupted", "Space to think before responding", "Reassurance that we're okay", "Resolution quickly", "A calm and measured tone", "To feel like I'm not being attacked"],
    tags: ["needs_in_conflict", "conflict_style"],
    weight: "high",
  },
  {
    id: "cf3",
    category: "conflict_style",
    text: "After an argument, how do you usually feel?",
    type: "choice",
    options: ["Ready to move on quickly", "Need time alone to recover", "Replay it mentally for hours", "Unresolved until it's talked through again", "Guilty regardless of what happened"],
    tags: ["post_conflict_pattern", "rumination", "emotional_recovery"],
    weight: "medium",
  },
  {
    id: "cf4",
    category: "conflict_style",
    text: "How do you feel when a conflict doesn't get resolved cleanly?",
    type: "choice",
    options: ["I can let it go eventually", "It lingers and affects my mood", "I need to revisit it", "I shut it out", "It erodes trust a little each time"],
    tags: ["unresolved_conflict", "post_conflict_pattern", "trust"],
    weight: "high",
  },
  {
    id: "cf5",
    category: "conflict_style",
    text: "When conflict happens, who do you think typically initiates resolution?",
    type: "choice",
    options: ["Usually me", "Usually my partner", "Depends on the situation", "Neither of us — things just cool off", "We both push to resolve it"],
    tags: ["conflict_resolution", "relationship_dynamic", "partner_perception"],
    weight: "medium",
  },
  {
    id: "cf6",
    category: "conflict_style",
    text: "How comfortable are you with confrontation in general?",
    type: "scale",
    tags: ["conflict_comfort", "directness", "conflict_avoidance"],
    weight: "high",
  },
  {
    id: "cf7",
    category: "conflict_style",
    text: "When you're in the middle of a heated moment, what helps you de-escalate?",
    type: "text",
    tags: ["de_escalation", "self_regulation", "conflict_style"],
    weight: "high",
  },
  {
    id: "cf8",
    category: "conflict_style",
    text: "How quickly do you typically cool down after a flare-up?",
    type: "scale",
    tags: ["emotional_recovery", "processing_style", "post_conflict_pattern"],
    weight: "medium",
  },
  {
    id: "cf9",
    category: "conflict_style",
    text: "After a disagreement, what helps you feel most \"repaired\" or reconnected?",
    type: "multi_choice_limited",
    max_select: 2,
    options: [
      "A genuine apology",
      "Changed behavior afterward",
      "Being understood emotionally",
      "Physical affection or closeness",
      "Time + space before reconnecting",
      "Talking it through calmly",
      "Something else",
    ],
    tags: ["repair_style", "post_conflict_pattern", "reconnection"],
    weight: "high",
  },
  {
    id: "cf10",
    category: "conflict_style",
    text: "After conflict, how quickly do you prefer to reconnect?",
    type: "choice",
    options: [
      "Immediately",
      "After a short cooling-off period",
      "Later that day",
      "The next day or later",
      "It depends on the situation",
    ],
    tags: ["repair_timeline", "post_conflict_pattern", "processing_style"],
    weight: "high",
  },
  {
    id: "cf11",
    category: "conflict_style",
    text: "When you realize you were wrong, what do you usually do next?",
    type: "multi_choice_limited",
    max_select: 2,
    options: [
      "Apologize",
      "Explain my perspective",
      "Try to change the behavior",
      "Need time before doing anything",
      "Feel overwhelmed and shut down",
      "Move on without addressing it",
      "Something else",
    ],
    tags: ["accountability", "repair_style", "conflict_style"],
    weight: "high",
  },

  // ─── ENERGY & SOCIAL ───────────────────────────────────────────────────────

  {
    id: "en1",
    category: "energy_social",
    text: "Being around people generally makes you feel:",
    type: "choice",
    options: ["Energized and alive", "Neutral — depends on the people", "Tired — I need recovery time after", "Drained almost always"],
    tags: ["social_energy", "introversion_extroversion"],
    weight: "medium",
  },
  {
    id: "en2",
    category: "energy_social",
    text: "After a long or difficult day, what do you most want from your partner?",
    type: "choice",
    options: ["To talk it all out", "Just quiet company — presence without words", "Physical affection without expectation", "Space to decompress alone first", "Distraction — something light and fun"],
    tags: ["recharge_style", "love_language", "needs_in_stress"],
    weight: "high",
  },
  {
    id: "en3",
    category: "energy_social",
    text: "How much does your energy level affect your ability to communicate well?",
    type: "scale",
    tags: ["energy_communication", "stress_response", "self_awareness"],
    weight: "high",
  },
  {
    id: "en4",
    category: "energy_social",
    text: "What drains you most in a day?",
    type: "multi_choice",
    options: ["Being around a lot of people", "Emotional labor", "Work pressure or deadlines", "Unresolved tension at home", "Feeling unproductive", "Too many obligations at once", "Feeling unseen or unappreciated"],
    tags: ["energy_drain", "stress_trigger", "needs"],
    weight: "high",
  },
  {
    id: "en5",
    category: "energy_social",
    text: "What recharges you fastest?",
    type: "multi_choice",
    options: ["Time alone in quiet", "Time together doing something simple", "Exercise or movement", "Creative activity", "A meaningful conversation", "Laughter and lightness", "Sleep or rest"],
    tags: ["recharge_style", "social_energy", "self_care"],
    weight: "high",
  },
  {
    id: "en6",
    category: "energy_social",
    text: "When you're drained, how does it affect how you show up in the relationship?",
    type: "text",
    tags: ["energy_communication", "partner_perception", "self_awareness"],
    weight: "high",
  },
  {
    id: "en7",
    category: "energy_social",
    text: "How much quality time with your partner do you feel you currently get in a typical week?",
    type: "scale",
    tags: ["quality_time", "relationship_satisfaction", "unmet_needs"],
    weight: "high",
  },

  // ─── DEEP REFLECTION ───────────────────────────────────────────────────────

  {
    id: "d1",
    category: "deep_reflection",
    text: "What patterns from your upbringing still show up in your relationships today?",
    type: "text",
    tags: ["childhood_patterns", "emotional_blueprint", "unresolved_patterns"],
    weight: "high",
  },
  {
    id: "d2",
    category: "deep_reflection",
    text: "What do you need emotionally but find hard to ask for?",
    type: "text",
    tags: ["unmet_needs", "vulnerability", "emotional_needs"],
    weight: "high",
  },
  {
    id: "d3",
    category: "deep_reflection",
    text: "What is the hardest thing for you to express to your partner?",
    type: "text",
    tags: ["vulnerability", "communication_gap", "emotional_expression"],
    weight: "high",
  },
  {
    id: "d4",
    category: "deep_reflection",
    text: "When you feel hurt, what do you usually do?",
    type: "choice",
    options: ["Express it immediately", "Withdraw until I've processed", "Act differently but don't explain", "Suppress it and move on", "Seek reassurance indirectly"],
    tags: ["hurt_response", "emotional_expression", "vulnerability"],
    weight: "high",
  },
  {
    id: "d5",
    category: "deep_reflection",
    text: "What do you wish your partner understood about you that you've never fully said out loud?",
    type: "text",
    tags: ["unspoken_needs", "partner_perception", "vulnerability"],
    weight: "high",
  },
  {
    id: "d6",
    category: "deep_reflection",
    text: "What fear do you carry into this relationship — even unconsciously?",
    type: "text",
    tags: ["attachment_fear", "vulnerability", "emotional_blueprint"],
    weight: "high",
  },
  {
    id: "d7",
    category: "deep_reflection",
    text: "How much do you believe you deserve to be fully loved as you are right now?",
    type: "scale",
    tags: ["self_worth", "vulnerability", "emotional_health"],
    weight: "high",
  },
  {
    id: "d8",
    category: "deep_reflection",
    text: "What version of yourself do you hide from your partner most?",
    type: "text",
    tags: ["authenticity", "vulnerability", "self_perception"],
    weight: "high",
  },
  {
    id: "d9",
    category: "deep_reflection",
    text: "When your partner does something that upsets you, what does it usually mean to you?",
    type: "multi_choice_limited",
    max_select: 2,
    options: [
      "They don't understand me",
      "I'm not a priority",
      "They don't care enough",
      "I'm being criticized or judged",
      "I'm not being heard",
      "They are overwhelmed / not intentional",
      "Something else",
    ],
    tags: ["emotional_meaning", "misunderstood_trigger", "attachment_pattern"],
    weight: "high",
  },
  {
    id: "d10",
    category: "deep_reflection",
    text: "When something hurts you, what happens internally first?",
    type: "multi_choice_limited",
    max_select: 2,
    options: [
      "I feel it deeply but don't show it",
      "I want to talk about it immediately",
      "I replay it in my head",
      "I shut down or withdraw",
      "I get frustrated or reactive",
      "I try to rationalize it",
      "Something else",
    ],
    tags: ["hurt_response", "emotional_processing", "vulnerability"],
    weight: "high",
  },

  // ─── FAMILY & UPBRINGING ───────────────────────────────────────────────────

  {
    id: "f1",
    category: "family_upbringing",
    text: "How was conflict handled in your household growing up?",
    type: "choice",
    options: ["Openly and constructively", "Avoided at all costs", "Loudly and explosively", "Passive-aggressively", "Inconsistently — it changed"],
    tags: ["childhood_patterns", "conflict_style", "emotional_blueprint"],
    weight: "high",
  },
  {
    id: "f2",
    category: "family_upbringing",
    text: "How emotionally expressive was your family when you were growing up?",
    type: "scale",
    tags: ["emotional_expressiveness", "childhood_patterns", "emotional_blueprint"],
    weight: "high",
  },
  {
    id: "f3",
    category: "family_upbringing",
    text: "What did love look like in your family growing up?",
    type: "text",
    tags: ["love_language", "attachment_style", "emotional_blueprint"],
    weight: "high",
  },
  {
    id: "f4",
    category: "family_upbringing",
    text: "What did you have to do to feel loved or approved of as a child?",
    type: "text",
    tags: ["attachment_pattern", "conditional_love", "emotional_blueprint"],
    weight: "high",
  },
  {
    id: "f5",
    category: "family_upbringing",
    text: "What did you vow — consciously or not — to do differently than your parents in relationships?",
    type: "text",
    tags: ["childhood_patterns", "growth_intention", "emotional_blueprint"],
    weight: "high",
  },
  {
    id: "f6",
    category: "family_upbringing",
    text: "What did you learn from your upbringing that has actually helped your relationship?",
    type: "text",
    tags: ["childhood_patterns", "strengths", "relationship_resources"],
    weight: "medium",
  },
  {
    id: "f7",
    category: "family_upbringing",
    text: "Which parent or caregiver do you think you're most like in how you handle relationships?",
    type: "text",
    tags: ["childhood_patterns", "attachment_style", "emotional_blueprint"],
    weight: "medium",
  },

  // ─── PARTNER PERCEPTION ────────────────────────────────────────────────────

  {
    id: "p1",
    category: "partner_perception",
    text: "How do you think your partner experiences you during conflict?",
    type: "multi_choice",
    options: ["Too intense", "Too distant", "Hard to read", "Too critical", "Supportive but reactive", "Reasonable but slow to engage", "Overwhelmed"],
    tags: ["self_awareness", "perceived_impact", "partner_perception"],
    weight: "high",
  },
  {
    id: "p2",
    category: "partner_perception",
    text: "What do you think frustrates your partner most about how you communicate?",
    type: "text",
    tags: ["partner_perception", "blind_spots", "communication_gap"],
    weight: "high",
  },
  {
    id: "p3",
    category: "partner_perception",
    text: "Where do you think you are most misunderstood by your partner?",
    type: "text",
    tags: ["misunderstanding_gap", "partner_perception", "self_awareness"],
    weight: "high",
  },
  {
    id: "p4",
    category: "partner_perception",
    text: "What do you think your partner needs from you that you don't give enough of?",
    type: "text",
    tags: ["blind_spots", "unmet_needs", "partner_perception"],
    weight: "high",
  },
  {
    id: "p5",
    category: "partner_perception",
    text: "What do you think your partner loves most about who you are?",
    type: "text",
    tags: ["strengths", "self_worth", "partner_perception"],
    weight: "medium",
  },
  {
    id: "p6",
    category: "partner_perception",
    text: "How accurately do you think your partner reads your emotions?",
    type: "scale",
    tags: ["emotional_attunement", "partner_perception", "communication_gap"],
    weight: "high",
  },
  {
    id: "p7",
    category: "partner_perception",
    text: "Is there something your partner does that you've never fully acknowledged is hard for you? Describe it.",
    type: "text",
    tags: ["unspoken_needs", "blind_spots", "vulnerability"],
    weight: "high",
  },
  {
    id: "p8",
    category: "partner_perception",
    text: "When conflict happens, what do you think your partner needs most from you?",
    type: "multi_choice_limited",
    max_select: 2,
    options: [
      "Understanding",
      "Listening",
      "Space",
      "Reassurance",
      "Affection",
      "Problem-solving",
      "Accountability",
      "I'm not sure",
    ],
    tags: ["partner_needs", "empathy", "partner_perception"],
    weight: "high",
  },

  // ─── NEEDS & VULNERABILITY ─────────────────────────────────────────────────

  {
    id: "nv1",
    category: "needs_vulnerability",
    text: "What do you need to feel safe enough to be fully honest?",
    type: "text",
    tags: ["emotional_safety", "vulnerability", "communication_need"],
    weight: "high",
  },
  {
    id: "nv2",
    category: "needs_vulnerability",
    text: "How do you let your partner know you need more support without saying it directly?",
    type: "text",
    tags: ["passive_communication", "unmet_needs", "emotional_expression"],
    weight: "high",
  },
  {
    id: "nv3",
    category: "needs_vulnerability",
    text: "When you feel disconnected from your partner, what does that look like for you?",
    type: "text",
    tags: ["disconnection", "attachment", "emotional_awareness"],
    weight: "high",
  },
  {
    id: "nv4",
    category: "needs_vulnerability",
    text: "How important is it to you to feel like a priority in your partner's life?",
    type: "scale",
    tags: ["need_for_validation", "attachment", "priority_need"],
    weight: "high",
  },
  {
    id: "nv5",
    category: "needs_vulnerability",
    text: "What does being truly supported look like to you?",
    type: "text",
    tags: ["support_style", "needs_in_conflict", "love_language"],
    weight: "high",
  },
  {
    id: "nv6",
    category: "needs_vulnerability",
    text: "What's something you've wanted to say for a while but haven't found the right moment?",
    type: "text",
    tags: ["unspoken_needs", "vulnerability", "communication_gap"],
    weight: "high",
  },
  {
    id: "nv7",
    category: "needs_vulnerability",
    text: "How comfortable are you receiving love, compliments, or care from your partner?",
    type: "scale",
    tags: ["vulnerability_comfort", "love_language", "self_worth"],
    weight: "medium",
  },
  {
    id: "nv8",
    category: "needs_vulnerability",
    text: "What makes you feel closest to your partner?",
    type: "text",
    tags: ["love_language", "connection", "relationship_satisfaction"],
    weight: "medium",
  },
  {
    id: "nv9",
    category: "needs_vulnerability",
    text: "When you're stressed or overwhelmed, what do you need most from your partner?",
    type: "multi_choice_limited",
    max_select: 2,
    options: [
      "To be understood emotionally",
      "To be listened to without interruption",
      "Reassurance",
      "Space and no pressure",
      "Physical affection",
      "Help solving the problem",
      "Distraction / lightness",
      "Something else",
    ],
    tags: ["needs_in_stress", "support_style", "love_language"],
    weight: "high",
  },
  {
    id: "nv10",
    category: "needs_vulnerability",
    text: "What tends to make you feel most alone in the relationship?",
    type: "multi_choice_limited",
    max_select: 2,
    options: [
      "Not being understood",
      "Not being listened to",
      "Lack of effort or follow-through",
      "Emotional distance",
      "Lack of affection",
      "Conflict not being resolved",
      "Being dismissed or minimized",
      "Something else",
    ],
    tags: ["loneliness_trigger", "disconnection", "unmet_needs"],
    weight: "high",
  },

  // ─── THEN VS NOW ───────────────────────────────────────────────────────────

  {
    id: "t1",
    category: "then_vs_now",
    text: "How did you handle conflict at the beginning of this relationship compared to now?",
    type: "text",
    tags: ["conflict_growth", "then_vs_now", "self_awareness"],
    weight: "high",
  },
  {
    id: "t2",
    category: "then_vs_now",
    text: "What's one thing you've genuinely changed about yourself in this relationship?",
    type: "text",
    tags: ["growth", "self_awareness", "then_vs_now"],
    weight: "high",
  },
  {
    id: "t3",
    category: "then_vs_now",
    text: "What pattern do you know you haven't fully resolved — even after 13 years?",
    type: "text",
    tags: ["unresolved_patterns", "growth_area", "self_awareness"],
    weight: "high",
  },
  {
    id: "t4",
    category: "then_vs_now",
    text: "How have your needs changed over the course of this relationship?",
    type: "text",
    tags: ["needs_evolution", "then_vs_now", "emotional_growth"],
    weight: "high",
  },
  {
    id: "t5",
    category: "then_vs_now",
    text: "What do you miss about earlier in this relationship?",
    type: "text",
    tags: ["relationship_evolution", "then_vs_now", "nostalgia"],
    weight: "medium",
  },
  {
    id: "t6",
    category: "then_vs_now",
    text: "What parts of yourself got quieter as life got busier — and do you miss them?",
    type: "text",
    tags: ["self_evolution", "then_vs_now", "authenticity"],
    weight: "high",
  },
  {
    id: "t7",
    category: "then_vs_now",
    text: "If the version of you from 10 years ago saw you now, what would surprise them most?",
    type: "text",
    tags: ["self_reflection", "growth", "then_vs_now"],
    weight: "medium",
  },
  {
    id: "t8",
    category: "then_vs_now",
    text: "How has your stubbornness — or certainty in yourself — evolved over the years?",
    type: "text",
    tags: ["stubbornness", "self_awareness", "emotional_growth"],
    weight: "high",
  },
];